### ISSUE TITLE
Is this a screenshot tool?

### ISSUE THREAD

**Issue by Yunnathai** [rumax/react-native-PixelsCatcher#12]
**Describe the bug**
Is this a screenshot tool?

**To Reproduce**

  - [ ] I checked the demo project and cannot reproduce the issue
  - [ ] I checked the demo project and the issue exists

  1. Render PDF with '...'
  2. Other actions '...'
  3. See error

**Expected behavior**

**Screenshots**

**Emulator information:**
  - Version
  - etc.

**Additional context**

**Comment by rumax** [comment]
Hi @jamninetyfive Thank you for the interest in the project. But would you be so kind to fill in template if you open the issue and and be more specific?

> Library for testing React Native UI components and screens
