### ISSUE TITLE
RN - 0.60  - Still requires normal packager

### ISSUE THREAD

**Issue by effortlesscoding** [rumax/react-native-PixelsCatcher#24]
**Describe the bug**
I cannot get the app to use indexSnapshot.js as the entry point, even after copy-pasting the .sh script from the demo project.

**To Reproduce**

  - [ X ] I checked the demo project and cannot reproduce the issue
  - [ X ] I checked the demo project and the issue exists

  1. Follow starting instructions for React Native 0.60
  2. Add indexSnapshot.js
  3. npm install packages for react-native-PixelsCatcher and fix the Pods issue in iOS (in 0.60, Pods are mandatory) so we can build the ios app from workspace
  4. fix app name, bundle name, etc. in package.json / pixel-catcher.json configuration files .
  5. run run_ios_debug.sh

**Expected behavior**

The IOS simulator will run the app and load the app based on indexSnapshot.js.

**Screenshots**
Instead, it just builds and installs the app as normal (on the iOS simulator specified in the json file), and when I run the app, it is still asking for the normal react-native packager, which is still using index.js as the entry point.

Obviously, that means screenshots are not created.

**Emulator information:**
  - "react-native": "0.60.4",
  - "react-native-save-view": "^0.1.2"
  -  "pixels-catcher": "^0.3.3",

**Additional context**
RN 0.60.
Here is my package.json configuration (ignore Android configuration... I haven't run Android yet):
```

  "PixelsCatcher": {
    "android": {
      "activityName": "MainActivity",
      "deviceName": "Nexus_5X",
      "packageName": "com.rumax.pixelscatcher.testapp",
      "snapshotsPath": "./snapshotsImages",
      "debug": {
        "deviceParams": ["-no-audio", "-no-snapshot"],
        "appFile": "./android/app/build/outputs/apk/debug/app-debug.apk"
      },
      "release": {
        "deviceParams": ["-no-audio", "-no-snapshot", "-no-window"],
        "appFile": "./android/app/build/outputs/apk/debug/app-debug.apk"
      }
    },
    "ios": {
      "deviceName": "iPhone XS",
      "packageName": "org.reactjs.native.example.sgrnvisualtests",
      "snapshotsPath": "./snapshots/ios/",
      "dev": {},
      "debug": {
        "appFile": "./ios/build/Build/Products/Debug-iphonesimulator/sgrnvisualtests.app",
        "activityName": ""
      }
    }
  }

```
Here is my run_ios_debug.sh file:
```
#!/bin/bash
set -x
set -e

export FORCE_BUNDLING=1
export RCT_NO_LAUNCH_PACKAGER=1

cd ios

BUILD_PATH="./build"
rm -rf $BUILD_PATH

xcrun xcodebuild \
  -scheme sgrnvisualtests \
  -workspace sgrnvisualtests.xcworkspace/ \
  -configuration Debug \
  -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.1' \
  -derivedDataPath $BUILD_PATH \
  ENTRY_FILE="indexSnapshot" \
  build

cd ..

./node_modules/.bin/pixels-catcher ios debug

```

**Comment by rumax** [comment]
Hi @zeroeffortdev, to be able to use `indexSnapshot.js`, you need to do some changes in iOS project. All these changes are done in the [demo project](https://github.com/rumax/react-native-PixelsCatcher/tree/master/demo), so you can check it. The changes are:

#### In `Build Phases` -> `Bundle React ...`:

<img width="572" alt="Screenshot 2019-08-08 at 14 08 34" src="https://user-images.githubusercontent.com/2707180/62702201-66cf7780-b9e6-11e9-9440-85ca5502e912.png">

#### Where `ENTRY_FILE` is defined with default value of `index`, to refer to `index.js`:

<img width="532" alt="Screenshot 2019-08-08 at 14 11 49" src="https://user-images.githubusercontent.com/2707180/62702338-c7f74b00-b9e6-11e9-9142-8f9a1b6b7638.png">


#### And in `AppDelegate.m`:

```
...

#define STRINGIZE(x) #x
#define STRINGIZE2(x) STRINGIZE(x)
#define INDEX_FILE @ STRINGIZE2(ENTRY_FILE)

...

#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:INDEX_FILE fallbackResource:nil];
#else

...
```

<hr>

Also, please, do not forget to ⭐️ the project if you like it or to indicate that you would like to see it maintained and supported in the future 😀
