### ISSUE TITLE
Allow concurrent runs

### ISSUE THREAD

**Issue by m-ruhl** [rumax/react-native-PixelsCatcher#39]
Hey,

we want to run iOS and Android Snapshot-Tests at the same time.
I think this is currently not possible, because both of them want to connect to Port 3000.

A possible solution would be that the platforms have different default ports, or the port is configurable.

Thanks

**Comment by rumax** [comment]
Please, try version `0.5.4`, where you can define [port](https://github.com/rumax/react-native-PixelsCatcher/blob/master/demo/pixels-catcher.json#L21) in the config. And in the app you can define ports per platform:

```
const baseUrl = Platform.select({
  android: 'http://10.0.2.2:3001',
  ios: 'http://127.0.0.1:3000',
});
```
