### ISSUE TITLE
Support Maps and Entry Animations

### ISSUE THREAD

**Issue by Rackles** [rumax/react-native-PixelsCatcher#46]
We have maps embedded in our views which take some time to load in iOS but don't get shown in Android at all. This causes the snapshots to be inconsistent when taken. Similar with loading animations and transitions that occur when a view gets loaded in.

One possible solution I could think of would be to allow a custom delay that gets applied when taken a snapshot.

**Comment by rumax** [comment]
Hi @Rackles is it what you are looking for? 

https://github.com/rumax/react-native-PixelsCatcher/blob/master/demo/indexSnapshot.js#L61

and 

https://github.com/rumax/react-native-PixelsCatcher/blob/master/demo/indexSnapshot.js#L71

In this case no delays at all and you do snapshot as soon as content is ready

**Comment by Rackles** [comment]
Oh yeah, thank you!! That might be it. 

For the future it might be helpful to add something like these comments into the Readme for others to find more easily.

**Comment by rumax** [comment]
Now it's in readme

```
Each Snapshot gets onReady property that is triggered after all interactions (InteractionManager) are completed. In case if it is not enough, which can be some network requests, etc., it is possible to do:

register animations by creating an interaction 'handle' and clearing it upon completion
override componentDidMount of the Snapshot and call onReady whenever you need it. WebViewTest in demo project for more details
```
