### ISSUE TITLE
Generate test report

### ISSUE THREAD

**Issue by m-ruhl** [rumax/react-native-PixelsCatcher#50]
It would be nice, if `pixels-catcher` would generate a test report like junit..

So in a CI-service you could see directly which tests have failed rather than looking in the logs.

**Comment by rumax** [comment]
Hi @m-ruhl, at this moment there is a report like this:

```
--------------------------------------------------------------------------------
All tests completed


    Name: AppSnapshot
    Render Time: 249 ms
    Total time: 1.278 sec
    Status: PASSED
    Message: -
  

    Name: AppSnapshotWithWrongRefImg
    Render Time: 99 ms
    Total time: 1.457 sec
    Status: FAILED
    Message: Images do not match: Files mismatch with 5088 pixels
  

    Name: someComponent
    Render Time: 31 ms
    Total time: 0.813 sec
    Status: PASSED
    Message: -
  

    Name: WebViewTest
    Render Time: 3657 ms
    Total time: 4.114 sec
    Status: FAILED
    Message: Images do not match: Files mismatch with 8375 pixels
  

    Name: longContent
    Render Time: 17 ms
    Total time: 0.927 sec
    Status: PASSED
    Message: -
  

Render time:
    min: 17ms (longContent)
    max: 3657ms (WebViewTest)
Total tests: 5
Passed tests: 3
Failed tests: 2
  - AppSnapshotWithWrongRefImg
  - WebViewTest
--------------------------------------------------------------------------------
```

which is printed at the end of tests. From this report for me the most useful is the last part:

```
Failed tests: 2
  - AppSnapshotWithWrongRefImg
  - WebViewTest
```

this is what I usually check if tests fail on CI and it seems to be enough for me to quickly find failing tests. Or did I miss something?

**Comment by m-ruhl** [comment]
I know you can get the info out of the logs.

There are still some benefits of having a test result file, that the CI server can parse:

- See failed tests right at the Pull/Merge-Requests
- Get Statistics (How many overall tests, which tests tend to fail over time)
- Attach failed screenshots (https://docs.gitlab.com/ee/ci/junit_test_reports.html#viewing-junit-screenshots-on-gitlab)

This is how it looks like for example: 
Gitlab (https://docs.gitlab.com/ee/ci/junit_test_reports.html#how-it-works)
AzureDevops (https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-continuous-test-results-after-build?view=azure-devops#tests-tab)

This is not super important.. just wanted to let you know my suggestion :)

**Comment by m-ruhl** [comment]
Thanks @rumax.. looks great 👍
