### ISSUE TITLE
Not compatible with different apps with debug build and release build.

### ISSUE THREAD

**Issue by mrtry** [rumax/react-native-PixelsCatcher#59]
**Is your feature request related to a problem? Please describe.**
The package name on Android is not compatible with different apps with debug build and release build.
As an example, this is an app that is an `io.mrtry.app.debug` in a debug build and an `io.mrtry.app` in a release build.
You may have the same problem on iOS.

**Describe the solution you'd like**
I'd like to be able to set `packageName` for `android.[debug,  release]`.
`android.packageName` is mandatory and `android.[debug,  release]. packageName` may be optional

**Comment by rumax** [comment]
Hi @mrtry, are you talking about `packageName` in the config? That is the name that is used in your project and that you  need to specify in the config. So:

> "packageName": "com.rumax.pixelscatcher.testapp",

has to be replaced with the actual name of your project.

**Comment by mrtry** [comment]
Thanks!

> Hi @mrtry, are you talking about packageName in the config?

Yes. 

> That is the name that is used in your project and that you need to specify in the config.

I fully understand that.

I'll explain in detail.

In Android, you may add suffix to the applicationId of the app in the debugging environment
See: https://developer.android.com/studio/build/build-variants#build-types

For example, it can be `io.mrtry.app.debug` for a debugging app and `io.mrtry.app` for a production app.

In this case, you need to specify the following to launch the app from `adb`.
**Debug environment:** `$ am start -n io.mrtry.app.debug/.activity.MainActivity`
**Production environment:** `$ am start -n io.mrtry.app/.activity.MainActivity`

But the current argument for adb looks like this
`$ am start -n ${packageName}/${packageName}.${activityName}`

If you don't specify the `packageName` as `io.mrtry.app.debug` in the debug environment and `io.mrtry.app` in the production environment It's not working properly.

**Comment by rumax** [comment]
HI @mrtry Can you, please, try

[pixels-catcher-0.10.0.tgz.zip](https://github.com/rumax/react-native-PixelsCatcher/files/4872961/pixels-catcher-0.10.0.tgz.zip)

and confirm that it works for you and fixes that issue. After that I can release new version

**Comment by mrtry** [comment]
@rumax 
Thanks!! 🙏 

Perhaps is this too...? 🤔 
https://github.com/rumax/react-native-PixelsCatcher/blob/e6d33c3f4bbf54dc2a7434b779b41815c8e4014b/src/runner/utils/device/AndroidDevice.js#L124

**Comment by rumax** [comment]
> Perhaps is this too...? 🤔

Thanks. I've completelly forgot about it 😀

<hr>

`0.10.0` with fixes is published
