### ISSUE TITLE
An option to clean "uploads" dir before run

### ISSUE THREAD

**Issue by m-ruhl** [rumax/react-native-PixelsCatcher#72]
Hey,

sometimes we delete tests or rename them, and therefore locally there are some old snapshots in the uploads dir.
It would be nice to have an option in the configuration, to remove all snapshots before a run.

**Comment by rumax** [comment]
Hi @m-ruhl , thanks for the suggestion. I think it might be a good idea to clean "uploads" folder and "diff" too. That should be possible when server is started. Another option (as a quick fix for you project) might be to use npm "pre" script or bash script (depends on how you implemented the testing).

**Comment by rumax** [comment]
Please, check 0.12.1 version
