### ISSUE TITLE
Get code coverage from the snapshots

### ISSUE THREAD

**Issue by LeoRedin** [rumax/react-native-PixelsCatcher#80]
**Is your feature request related to a problem? Please describe.**
I can't seem to get code coverage from those snapshots and I really wanted that to happen.

**Describe the solution you'd like**
I wanted to have some sort of cli command like _pixels-catcher platform coverage_ and then generate some report of the code coverage used inside the screenshots.

**Describe alternatives you've considered**
I have tried using istanbuljs to instrument the code and managed to get some info but not always, I think because jest creates some variables that I am using. Would be really nice if it came bundled with a native solution.

**Comment by rumax** [comment]
Hi @LeoRedin, that can be a good feature, but I would say for test coverage it is better to use unit tests. Otherwise I even not sure how coverage needs to be combined between different tests like UI, unit, e2e, etc.
