### ISSUE TITLE
Right vertical lines: Broken snapshot tests by local recorded iPhone Simulator uploads

### ISSUE THREAD

**Issue by shalfknight** [rumax/react-native-PixelsCatcher#83]
It is not an actual bug to the testing framework PixelsCatcer but I detected a missbehavior on local running iOS Simulators breaking snapshot tests for iOS.
Maybe you have made the same observations and can provide a good workaround or even a fix for that.

**Describing the "bug"**
- When running snapshot tests in our Azure pipeline using a vmImage _macOS-11_, our snapshot tests start failing for, let's say, "ghost button like" components.
- After some research, we recognized that the recorded screens from our local iPhone Simulator running on _Mac OS X 12.x_ do not render vertical lines properly on the right hand side of the screen.
The pipeline, also using a simulator, renders the views properly. Same for real iPhone devices.

Attached you can see the pipeline diff and the depiction on devices / pipeline simulator next to the local simulators snapshot where the right vertical lines are rendered a bit thicker.

### Diff

![PairingScreen - empty failure - lightDiff](https://user-images.githubusercontent.com/12291934/160588823-457b178d-784a-400d-b873-efabec1043e7.png)
https://github.com/shalfknight/vertical-line-bug/blob/main/bug/PairingScreen%20-%20empty%20failure%20-%20lightDiff.png

### Pipeline & Device Rendering

![PairingScreen - empty failure - lightActual](https://user-images.githubusercontent.com/12291934/160588860-12a713ce-9430-4252-bb2b-23179cbe0655.png)
https://github.com/shalfknight/vertical-line-bug/blob/main/bug/PairingScreen%20-%20empty%20failure%20-%20lightActual.png

### Local iPhone Simulator with wrong rendering

![PairingScreen - empty failure - lightReference](https://user-images.githubusercontent.com/12291934/160588878-7c461b4e-3245-4ea0-8c11-443dc04bd8cf.png)
https://github.com/shalfknight/vertical-line-bug/blob/main/bug/PairingScreen%20-%20empty%20failure%20-%20lightReference.png

**To Reproduce**

I created a very minimalstic demo project applying the small notification box from the previous screens.

https://github.com/shalfknight/vertical-line-bug

**Expected behavior**
When deploying it on an simulator, you should see that the right grey line is a bit thicker than the other grey lines

![VerticalLineBug](https://user-images.githubusercontent.com/12291934/160596729-3ed63b2e-7427-4b81-b073-b6f785c69e20.png)
https://github.com/shalfknight/vertical-line-bug/blob/main/bug/VerticalLine-Simulator.png

Deploying it to the device shows everything at its place

![VerticalLine-Device](https://user-images.githubusercontent.com/12291934/160601536-b6ffec88-ac17-45c9-9875-b4f61edafafe.jpeg)
https://github.com/shalfknight/vertical-line-bug/blob/main/bug/VerticalLine-Device.jpeg

**Simulator information:**
- It does not matter if it is an iPhone 8, iPhone 8 Plus or iPhone Pro Max 13
- Even different iOS versions do not matter
The behavior is always the same rendering a thicker vertical line for such components

Did you already observe something similar breaking snapshot tests that way?

Kind regards
Stefan

**Comment by rumax** [comment]
Hi @shalfknight, I didn't experience this kind if issue. Can you try to add some delays, let's say 1 sec to be sure that rendering is completed. You can do like it is done here https://github.com/rumax/react-native-PixelsCatcher/blob/master/demo/indexSnapshot.js#L77

```
componentDidMount() {
      // override default componentDidMount from Snapshot to delay it
      setTimeout(() => {
         this.props.onReady();
      }, 1000);
}
```

Otherwise maybe there is some difference between simulators. Do you create them with the same scrip both locally and on CI?

**Comment by shalfknight** [comment]
Hello @rumax 

Introducing timeouts for rendering did not change the behavior at all.
We also do not use a special script for simulator generation, we are just using the simulators which can be installed on Mac OS X. Nothing fancy done here at all as well.

Thereby it is so confusing that the simulators start failing for this kind of UI element, regardless if it is used in our main customer project nor in the simple demo project to reproduce this error: https://github.com/shalfknight/vertical-line-bug/

Does it work for you with our demo project?

**Comment by rumax** [comment]
> Hello @rumax
> 
> Introducing timeouts for rendering did not change the behavior at all. We also do not use a special script for simulator generation, we are just using the simulators which can be installed on Mac OS X. Nothing fancy done here at all as well.
> 
> Thereby it is so confusing that the simulators start failing for this kind of UI element, regardless if it is used in our main customer project nor in the simple demo project to reproduce this error: https://github.com/shalfknight/vertical-line-bug/
> 
> Does it work for you with our demo project?

Hi @shalfknight , I've tried your project locally and do not see any issues

iPhone 8:

> 0    │ 'Vertical Line Bug Screen' │ 'PASSED' │ 0.255 │   0.069 

<img width="375" alt="Vertical Line Bug Screen" src="https://user-images.githubusercontent.com/2707180/189347304-7385630e-e635-453f-8e0e-f05de3c06e58.png">


Same for iPhone 13

![Vertical Line Bug Screen](https://user-images.githubusercontent.com/2707180/189347403-21ea5a6a-afd9-4057-a4f3-b9c04aa43ada.png)

Border seems to be correct, according to definition

**Comment by shalfknight** [comment]
Thank you for testing!

On the one side I am becalmed that there is no issue in particular with pixels-catcher 👍

On the other side: It is really strange that this behavior occurs only on my team's local development machines. Nevermind, maybe time will tell one day what is causing that issue on our side. And if we should ever figure out that, we will document it here to prevent you from further headaches 😉
