### ISSUE TITLE
Boot of current Android emulator is not properly detected and pixels catcher runs into timeout

### ISSUE THREAD

**Issue by ow9t** [rumax/react-native-PixelsCatcher#94]
When running a current version of the Android emulator, the pixels catcher is not properly detecting the boot of the device, because it is awaiting the case-sensitive message `'boot completed'` (cp. https://github.com/rumax/react-native-PixelsCatcher/blob/master/src/runner/utils/device/AndroidEmulator.ts#L116), however, the emulator is actually sending the message `'Boot completed'`.
To fix this issue, the matching of the message should be done in a case-insensitive manner.

**To Reproduce**

  - [ ] I checked the demo project and cannot reproduce the issue
  - [x] I checked the demo project and the issue exists
  
  1. Configure android as per documentation
  2. Build apk
  3. Run `./node_modules/.bin/pixels-catcher android CONFIGURATION`

**Expected behavior**
Pixels catcher should properly detect the boot of the Android emulator and continue by installing the apk.

**Screenshots**
![pixels-catcher-timeout](https://github.com/rumax/react-native-PixelsCatcher/assets/66011329/0f33d2aa-da17-4d1e-a94e-0dca9b80ab78)

**Emulator information:**
  - Android emulator Version 33.1.24.0 (build_id 11237101)
  - pixels-catcher Version 0.13.0

**Comment by rumax** [comment]
Version 0.13.1 is published
